sudo: required
services:
    - docker
    
before_install:
    - docker build -t tomasoares/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run tomasoares/react-test npm test -- --coverage
    
after_success:
    - docker build -t tomasoares/dockercourse-multi-client ./client
    - docker build -t tomasoares/dockercourse-multi-nginx  ./nginx
    - docker build -t tomasoares/dockercourse-multi-server ./server
    - docker build -t tomasoares/dockercourse-multi-worker ./worker
    
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #Take those images and push them to docker hub
    - docker push tomasoares/dockercourse-multi-client
    - docker push tomasoares/dockercourse-multi-nginx
    - docker push tomasoares/dockercourse-multi-server
    - docker push tomasoares/dockercourse-multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-267699482760
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY